### ISSUE TITLE
Unboxed Consulting Sapphire Sponsor

### ISSUE THREAD

**Issue by marcheiligers** [Rubyfuza/rubyfuza-site#5]
For me todo:
- [x] Confirm blurb and link
- [x] Confirm logo

Once we have those, @Ruberto:
- [x] Add Unboxed to the site

**Comment by marcheiligers** [comment]
Unboxed is rebranding to drop the "Consulting". Blurb, link and logo still to be confirmed.

**Comment by Ruberto** [comment]
Ok, ill wait on them.

**Comment by marcheiligers** [comment]
Blurb changes to "We’re Unboxed. We collaborate to grow ideas for digital products and services. Then we build them. We also improve the way organisations works. We do this through agile and lean techniques, using Ruby on Rails."

Link and branding stays the same for now.
